version: '3.8'
services:
  back:
    build: ./back
    container_name: backend
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules
  front:
    build: ./front
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
